/* -LICENSE-START-
 ** Copyright (c) 2018 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
 ** OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 ** THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

// Minimal derivative of the Blackmagic RAW SDK ExtractFrame sample.  It decodes
// one frame at a time at SDK quarter resolution and writes packed RGBAU8 frames
// to stdout for ffmpeg.  Diagnostics are always written to stderr.
#include "BlackmagicRawAPI.h"

#include <cstdio>
#include <cstring>
#include <iostream>
#include <limits>

static const BlackmagicRawResourceFormat kResourceFormat = blackmagicRawResourceFormatRGBAU8;
static const BlackmagicRawResolutionScale kResolutionScale = blackmagicRawResolutionScaleQuarter;

static bool ParseUint64(const char* text, uint64_t* value) {
	if (*text == '\0') return false;
	uint64_t parsed = 0;
	for (const char* p = text; *p != '\0'; ++p) {
		if (*p < '0' || *p > '9') return false;
		const uint64_t digit = static_cast<uint64_t>(*p - '0');
		if (parsed > (std::numeric_limits<uint64_t>::max() - digit) / 10) return false;
		parsed = parsed * 10 + digit;
	}
	*value = parsed;
	return true;
}

class Callback final : public IBlackmagicRawCallback {
public:
	bool writeRaw = false;
	bool complete = false;
	bool succeeded = false;
	uint32_t width = 0;
	uint32_t height = 0;

	void Reset() { complete = false; succeeded = false; width = 0; height = 0; }

	void ReadComplete(IBlackmagicRawJob* readJob, HRESULT result, IBlackmagicRawFrame* frame) override {
		IBlackmagicRawJob* processJob = nullptr;
		if (SUCCEEDED(result)) result = frame->SetResourceFormat(kResourceFormat);
		if (SUCCEEDED(result)) result = frame->SetResolutionScale(kResolutionScale);
		if (SUCCEEDED(result)) result = frame->CreateJobDecodeAndProcessFrame(nullptr, nullptr, &processJob);
		if (SUCCEEDED(result)) result = processJob->Submit();
		if (FAILED(result)) {
			std::cerr << "Decode setup failed (HRESULT=" << result << ")\n";
			complete = true;
		}
		if (processJob != nullptr && FAILED(result)) processJob->Release();
		readJob->Release();
	}

	void ProcessComplete(IBlackmagicRawJob* job, HRESULT result, IBlackmagicRawProcessedImage* image) override {
		uint32_t sizeBytes = 0;
		void* pixels = nullptr;
		if (SUCCEEDED(result)) result = image->GetWidth(&width);
		if (SUCCEEDED(result)) result = image->GetHeight(&height);
		if (SUCCEEDED(result)) result = image->GetResourceSizeBytes(&sizeBytes);
		if (SUCCEEDED(result)) result = image->GetResource(&pixels);
		const uint64_t expected = static_cast<uint64_t>(width) * height * 4;
		if (SUCCEEDED(result) && sizeBytes != expected) {
			std::cerr << "Unexpected RGBA buffer size: " << sizeBytes << " (expected " << expected << ")\n";
			result = E_FAIL;
		}
		if (SUCCEEDED(result) && writeRaw && std::fwrite(pixels, 1, sizeBytes, stdout) != sizeBytes) {
			std::cerr << "Failed writing raw RGBA frame\n";
			result = E_FAIL;
		}
		if (FAILED(result)) std::cerr << "Decode processing failed (HRESULT=" << result << ")\n";
		succeeded = SUCCEEDED(result);
		complete = true;
		job->Release();
	}

	void DecodeComplete(IBlackmagicRawJob*, HRESULT) override {}
	void TrimProgress(IBlackmagicRawJob*, float) override {}
	void TrimComplete(IBlackmagicRawJob*, HRESULT) override {}
	void SidecarMetadataParseWarning(IBlackmagicRawClip*, CFStringRef, uint32_t, CFStringRef) override {}
	void SidecarMetadataParseError(IBlackmagicRawClip*, CFStringRef, uint32_t, CFStringRef) override {}
	void PreparePipelineComplete(void*, HRESULT) override {}
	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID, LPVOID*) override { return E_NOTIMPL; }
	ULONG STDMETHODCALLTYPE AddRef() override { return 0; }
	ULONG STDMETHODCALLTYPE Release() override { return 0; }
};

int main(int argc, const char* argv[]) {
	const bool infoOnly = argc == 3 && std::strcmp(argv[1], "--info") == 0;
	const bool rawAll = argc == 3 && std::strcmp(argv[1], "--raw") == 0;
	const bool rawRange = argc == 5 && std::strcmp(argv[1], "--range") == 0;
	if (!infoOnly && !rawAll && !rawRange) {
		std::cerr << "Usage: " << argv[0] << " --info|--raw clip.braw\n"
			<< "       " << argv[0] << " --range clip.braw START_FRAME FRAME_COUNT\n";
		return 2;
	}
	uint64_t startFrame = 0;
	uint64_t framesToDecode = 0;
	if (rawRange && (!ParseUint64(argv[3], &startFrame) || !ParseUint64(argv[4], &framesToDecode) || framesToDecode == 0)) {
		std::cerr << "START_FRAME must be nonnegative and FRAME_COUNT must be positive decimal integers\n";
		return 2;
	}
	CFStringRef clipName = CFStringCreateWithCString(nullptr, argv[2], kCFStringEncodingUTF8);
	IBlackmagicRawFactory* factory = CreateBlackmagicRawFactoryInstanceFromPath(
		CFSTR("/Applications/Blackmagic RAW/Blackmagic RAW SDK/Mac/Libraries"));
	IBlackmagicRaw* codec = nullptr;
	IBlackmagicRawClip* clip = nullptr;
	Callback callback;
	HRESULT result = factory == nullptr ? E_FAIL : factory->CreateCodec(&codec);
	if (SUCCEEDED(result)) result = codec->OpenClip(clipName, &clip);
	if (SUCCEEDED(result)) result = codec->SetCallback(&callback);
	uint64_t frameCount = 0;
	float frameRate = 0;
	if (SUCCEEDED(result)) result = clip->GetFrameCount(&frameCount);
	if (SUCCEEDED(result)) result = clip->GetFrameRate(&frameRate);
	if (SUCCEEDED(result) && rawRange && (startFrame > frameCount || framesToDecode > frameCount - startFrame)) {
		std::cerr << "Requested frame range is outside clip frame count " << frameCount << "\n";
		result = E_INVALIDARG;
	}
	if (infoOnly) framesToDecode = 1;
	if (rawAll) framesToDecode = frameCount;
	callback.writeRaw = rawAll || rawRange;
	for (uint64_t offset = 0; SUCCEEDED(result) && offset < framesToDecode; ++offset) {
		IBlackmagicRawJob* readJob = nullptr;
		callback.Reset();
		result = clip->CreateJobReadFrame(startFrame + offset, &readJob);
		if (SUCCEEDED(result)) result = readJob->Submit();
		if (FAILED(result) && readJob != nullptr) readJob->Release();
		if (SUCCEEDED(result)) codec->FlushJobs();
		if (!callback.complete || !callback.succeeded) result = E_FAIL;
	}
	if (SUCCEEDED(result) && infoOnly) {
		std::cout << "width=" << callback.width << " height=" << callback.height
			<< " fps=" << frameRate << " frames=" << frameCount << " scale=quarter\n";
	}
	if (clip != nullptr) clip->Release();
	if (codec != nullptr) codec->Release();
	if (factory != nullptr) factory->Release();
	CFRelease(clipName);
	if (FAILED(result)) std::cerr << "BRAW decode failed (HRESULT=" << result << ")\n";
	return SUCCEEDED(result) ? 0 : 1;
}
